version: '3'
services: 
  mongodb:
    image: mongo
    container_name: mi-mongo
    restart: always
    volumes:
      - mongo-vol:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12356
    networks:
        mongo-node-net:
          ipv4_address: 172.40.0.10
  nodejs:
    image: mi-node-image
    container_name: mi-node
    ports:
      - "8080:8080"
    networks:
        mongo-node-net:
          ipv4_address: 172.40.0.11
        node-nginx-net:
          ipv4_address: 172.80.0.10
    depends_on:
      - mongodb
  nginx:
    image: nginx:alpine
    container_name: mi-nginx
    ports:
      - "8082:80"
    volumes:
      - mongo-vol
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    networks:
        node-nginx-net:
          ipv4_address: 172.80.0.11
    depends_on:
      - nodejs
volumes:
  mongo-vol:
networks:
  mongo-node-net:
    ipam:
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    ipam:
      config:
        - subnet: 172.80.0.0/16
