version: '3'
services: 
  mongodb:
    image: mongo
    container_name: mi-mongo
    volumes:
      - mongo-vol:/data/db
    networks:
      - mongo-node-net:
          ipv4_address: 172.40.0.10
  nodejs:
    image: mi-node-image
    container_name: mi-node
    working_dir: /app
    volumes:
      - mongo-vol
    ports:
      - 3000:3000
    networks:
      - mongo-node-net:
          ipv4_address: 172.40.0.11  
      - node-nginx-net:
          ipv4_address: 172.80.0.10
    depends_on:
      - mongodb
  nginx:
    image: mi-nginx
    container_name: mi-nginx
    ports:
      - 8080:80
    volumes:
      - mongo-vol
    networks:
      - node-nginx-net:
          ipv4_address: 172.80.0.11
    depends_on:
      - nodejs
volumes:
  mongo-vol:
networks:
  mongo-node-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.40.0.0/16
  node-nginx-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.80.0.0/16
