#1.-Docker compose de despliegue de mongo y mongo-express
version: '3'
services:
  mongodb:
    image: mongo
    container_name: mi-mongo
    volumes:
      - mi-volumen:/data/db
    networks:
      - mi-red
  mongo-express:
    image: mongo-express
    container_name: mi-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=123456
    networks:
      - mi-red
    depends_on:
      - mongodb

volumes:
  mi-volumen:

networks:
  mi-red:
